### ISSUE TITLE
Cannot pass lists

### ISSUE THREAD

**Issue by ajs124** [msteen/nix-prefetch#1] opened 2019-03-19 03:52 UTC
Some fetchers (like fetchrepoproject) take lists, which I cannot seem to figure out how to pass to nix-prefetch.

Using `--input nix` or `--input json` fails with jq errors, regular command line arguments seem to turn the list into a string.

I tried some more things, but I doubt they are relevant. I would love to be able to use nix-prefetch, but without being able to pass lists to it somehow, it sadly does not fulfill my requirements.

**Comment by msteen** [comment] 2019-03-20 17:03
Thank you for reporting this! I indeed made `--input` unnecessarily restrictive in that it only allows string arguments, considering how passing arguments via the command line does allow arbitrary expressions via e.g. `--<name> --expr '[ 1 2 ]'`. I have modified the implementation of `--input` for `nix` (now even allows an arbitrary Nix expression resulting in an attribute set of fetcher arguments) and `json`, which I will publish once I have done some more testing. So you can either wait for that push or workaround it for now with `--<name> --expr '[ 1 2 ]'`.

**Comment by ajs124** [comment] 2019-03-20 23:39
Thanks for looking into this! (and writing nix-prefetch in the first place)

Using `--input` was already my workaround, because I hadn't figured out that `--expr` can be used this way.

**Comment by msteen** [comment] 2019-03-22 10:22
I just pushed the necessary fixes. Could you verify if it now works like you expected it to? Then I can tag it as the new version. My goal for `nix-prefetch` is to have it cover all prefetching needs for Nix packages, so let me know if there are still other things withholding you from using it for your use case. Also if you have any ideas on how to improve it, any feedback is most welcome.

**Comment by ajs124** [comment] 2019-03-22 23:14
Yep, seems to work. Although I just now figured out that apparently the declarative hydra configuration does not take JSON lists. Oh well…

Another issue I've run into is this: `error: getting status of '/run/user/1000/nix-prefetch/prelude.nix': No such file or directory`.
This error seems to appear when running nix-prefetch in an environment where `<nixpkgs>` refers to something pre 19.03. I have a [workaround](https://github.com/ajs124/NixDroid/blob/d1ca95da91fc2d3819774efde7e208eb0269fde3/hydra/prefetch.nix#L18) for that, though.

**Comment by msteen** [comment] 2019-03-23 08:53
Great to hear its working for you. About the other issue, I created #2 and think I have found the cause. It likely has to do with `nixpkgs-overlays` on `NIX_PATH` rather than `nixpkgs`, but I will let you know when I pushed the fix. I will be closing this issue now, since list passing issue should be fixed now.

**Closed by msteen** 2019-03-23 08:53 UTC
